import "../../CommonImports";
import "../../Core/core.css";
import "./HeaderCommandBar.css";
import * as React from "react";
import { IIconProps } from '../Icon/Icon.Props';
import { IMenuItem } from '../../Menu';
import { IHeaderCommandBarItem } from "./HeaderCommandBar.Props";
export declare function getFilterItem(onActivate: (menuItem: IMenuItem, event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => boolean | void, isFiltering: boolean, important?: boolean, label?: string): IHeaderCommandBarItem;
export declare function getFilterItemIconProps(isFiltering: boolean): IIconProps;
export declare function getFullScreenItem(onActivate: (menuItem: IMenuItem, event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => boolean | void, fullscreen: boolean, important?: boolean): IHeaderCommandBarItem;
export declare function toggleFullScreen(newFullScreenState: boolean): void;
